name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Publish module
      run: |
        Install-Module -Name PowerShellGet -Force -AllowPrerelease -Scope CurrentUser -Repository PSGallery
        Publish-Module -Path $env:GITHUB_WORKSPACE -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }}
